export const actionTypes = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_ITEMS: "SET_USER_ITEMS",
  SET_USER_MORE_INFO: "SET_USER_MORE_INFO",
  SET_MOVERS_DATA: "SET_MOVERS_DATA",
  SET_PAYMENT_SUCCESS: "SET_PAYMENT_SUCCESS",
  RESET_MOVERS_DATA: "RESET_MOVERS_DATA",
  RESET_USER_INFO: "RESET_USER_INFO",
  RESET_PAYMENT_SUCCESS: "RESET_PAYMENT_SUCCESS",
};
